repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.2  # latest stable version as of 12/8/2024
    hooks:
      # this will run ruff as configured in pyproject.toml
      - id: ruff
        args: ["--verbose"]
        language_version: python3

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.2  # latest stable version as of 12/8/2024
    hooks:
      # this is a second ruff pass, --isolated to ignore pyproject.toml, w/ other rules 
      # (Performance, Bestpractices) I want to warn but not fail on violations of 
      - id: ruff
        language_version: python3
        args:
          - --isolated
          - --verbose
          - --extend-select
          - P,B,C90
          - --severity
          - warning

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0  # latest stable version as of 12/8/2024
    hooks:
      - id: mypy
        args:
          - --disable-error-code
          - attr-defined
        language_version: python3
