repos:
  # Linting with ruff; this will run ruff as configured in pyproject.toml. Fail on violations.
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.2  # latest stable version as of 12/8/2024
    hooks:
      - id: ruff
        args: ["--verbose"]
        language_version: python3

    # this is a second ruff pass, --isolated to ignore pyproject.toml, w/ other rules 
    # (Performance, Bestpractices) I want to warn but not fail on violations of 
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.2  # latest stable version as of 12/8/2024
    hooks:
      - id: ruff
        language_version: python3
        args:
          - --isolated
          - --verbose
          - --extend-select
          - P,B,C90
          - --severity
          - warning

  # Static type checking with pyright
repos:
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.390
    hooks:
    - id: pyright