name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup environment
      uses: ./.github/actions/setup-env
      with:
        dependencies: "ruff 'pyright[nodejs]'"
    
    - name: Run Ruff (Linter)
      run: uv run ruff check . --verbose --config pyproject.toml

    - name: Run Pyright (Type-Checker)
      run: uv run pyright

  integration_tests:
    name: Health Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup environment
      uses: ./.github/actions/setup-env
      with:
        dependencies: "requests"
    
    - name: Run health check
      run: uv run python tests/health_check.py
