name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  setup:
    name: Setup Python and UV Venv
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.8'

    - name: Debug - Check initial directory
      run: |
        pwd
        ls -la

    - name: Install uv, create & activate venv
      run: |
        pip install uv
        uv venv
        source .venv/bin/activate

    - name: Debug - Check venv structure
      run: |
        echo "Current directory structure:"
        ls -la
        echo "\nVenv directory structure:"
        ls -la .venv || echo "No .venv directory found"
        echo "\nAbsolute path check:"
        readlink -f .venv

    - name: Install shared dependencies
      run: |
        source .venv/bin/activate
        uv pip install ruff mypy requests

    - name: Debug - Final venv check
      run: |
        echo "Final directory structure:"
        ls -la
        echo "\nFinal venv contents:"
        ls -la .venv/
        echo "\nFinal bin contents:"
        ls -la .venv/bin/

    - name: Save venv as artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-venv
        path: .venv/
        retention-days: 1
        if-no-files-found: error
