name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  setup:
    name: Setup Python and UV Venv
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.8'

    - name: Install uv, create & activate venv
      run: |
        pip install uv
        uv venv
        source .venv/bin/activate

    - name: Install shared dependencies
      run: |
        uv pip install ruff mypy requests

    - name: save .venv as artifact for successive ci/cd jobs/steps
      uses: actions/upload-artifact@v3
      with:
        name: venv
        path: .venv

  lint:
    name: Lint Code
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download and activate venv
      run: |
        tar -xzf $(actions/download-artifact@v3 --artifact-name venv)
        source .venv/bin/activate

    - name: Run Ruff
      run: |
        uv run ruff check . \
          --verbose \
          --config pyproject.toml

    - name: Run MyPy
      run: |
        uv run mypy app.py \
          --config pyproject.toml \
          --disable-error-code attr-defined

  health_check:
    name: Health Check
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download and activate venv
      run: |
        tar -xzf $(actions/download-artifact@v3 --artifact-name venv)
        source .venv/bin/activate

    - name: Install additional dependencies
      run: uv pip install requests
    
    - name: Run health check
      run: python tests/health_check.py
